apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-demo-deployment
  labels:
    app: prom-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prom-demo
  template:
    metadata:
      labels:
        app: prom-demo
    spec:
      containers:
      - name: prom-demo-container
        image: ghcr.io/tkubica12/cloud-arch-app-data/monitoring_prometheus:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: prom-demo-service
  labels:
    app.kubernetes.io/name: prom-demo-service
spec:
  selector:
    app: prom-demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-demo-service-monitor
  labels:
    app: prom-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prom-demo-service
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    scheme: http
    path: /metrics
    interval: 15s
